### ISSUE TITLE
Website is Down 10/12

### ISSUE THREAD

**Issue by MichaelJamesParsons** [unkso/pages#2]
I am unable to access the website. Two other members have confirmed they're experiencing the same problem.

Is anyone working on the website? If this occurs in the future, do we have a dedicated slack channel (or other messaging platform) to notify each other of these situations?

**Comment by ELD** [comment]
I'm aware of it. I am contacting support to assist. They rolled out what seems to be a bad firewall update. I can still SSH into the server and you can still ping it, but it must be blocking port 80/443 for some odd reason.

**Comment by ELD** [comment]
It's back up.
